#!/usr/bin/env bash
set -euo pipefail

# Regenerate docs/specs/INDEX.md from spec files in
# docs/specs/{open,closed}/**/*.md.
#
# Reads the front-matter `id`, `title`, `type`, `status`, `priority`,
# `updated` of each file. Sorted by id ascending. The generated
# INDEX.md is plain Markdown; do not edit it by hand.
ROOT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." >/dev/null 2>&1 && pwd)"
cd "${ROOT_DIR}"

INDEX="docs/specs/INDEX.md"
TMP="$(mktemp)"

cat > "${TMP}" <<'EOF'
# Spec index

Auto-generated by `scripts/update-spec-index.sh`. Do not edit by hand —
your changes will be overwritten.

| ID | Title | Type | Status | Priority | Updated |
| -- | ----- | ---- | ------ | -------- | ------- |
EOF

ROWS="$(mktemp)"

SPEC_FILES="$(find docs/specs/open docs/specs/closed -type f -name '*.md' 2>/dev/null \
  | grep -v -E '/(README|INDEX)\.md$' || true)"

while IFS= read -r f; do
  [[ -z "${f}" ]] && continue
  id="$(awk '/^id:/{print $2; exit}' "${f}")"
  title="$(awk -F': ' '/^title:/{$1=""; sub(/^ /,""); print; exit}' "${f}")"
  type="$(awk '/^type:/{print $2; exit}' "${f}")"
  status="$(awk '/^status:/{print $2; exit}' "${f}")"
  priority="$(awk '/^priority:/{print $2; exit}' "${f}")"
  updated="$(awk '/^updated:/{print $2; exit}' "${f}")"
  if [[ -z "${id}" ]]; then continue; fi
  printf "| %s | %s | %s | %s | %s | %s |\n" \
    "${id}" "${title:-}" "${type:-}" "${status:-}" "${priority:-}" "${updated:-}" \
    >> "${ROWS}"
done <<< "${SPEC_FILES}"

if [[ -s "${ROWS}" ]]; then
  sort -u "${ROWS}" >> "${TMP}"
else
  echo "| _no specs yet_ |  |  |  |  |  |" >> "${TMP}"
fi

mv "${TMP}" "${INDEX}"
rm -f "${ROWS}"
echo "==> Wrote ${INDEX}"
